### ISSUE TITLE
Latest geode crashes on 10.15.7 MacOS

### ISSUE THREAD

**Issue by speedyfriend433** [geode-sdk/geode#1022] opened 2024-07-31 01:40 UTC
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

MacOS

### Geode Version

v3.4.0

### Mods Installed

Before installing mods, it. Crashes at launcher 
So mod folder is not even available 

### Steps to Reproduce

Install mac installer from official github
Inject geode to steam gd path
Launch steam
Crash

**Comment by qimiko** [comment] 2024-07-31 02:30
duplicate of #991

**Closed by qimiko** 2024-07-31 02:30 UTC
Labels: crash, unverified
