### ISSUE TITLE
Game crashes when opening profile

### ISSUE THREAD

**Issue by ilovelampadaire** [geode-sdk/geode#780] opened 2024-05-21 17:47 UTC
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.26

### Mods Installed

x | [v1.0.5] alphalaneous.happy_textures
x | [v1.0.1] alvy.movecommentdown
x | [v1.8.0] beat.click-sound
x | [v1.0.4] bitz.moregames
x | [v1.0.3] capeling.coloured-wave-trail
x | [v1.0.4] cdc.level_thumbnails
x | [v1.0.0] cdc.statuses
x | [v4.1.7] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.0.3] dogotrigger.level_history
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.1] elsai.easing_preview
x | [v1.5.7] geode.custom-keybinds
x | [v2.0.0-beta.26] geode.loader
x | [v1.10.2] geode.node-ids
x | [v1.2.0] hjfod.bettersave
x | [v1.0.5] hjfod.gdshare
x | [v1.1.0] hjfod.gmd-api
x | [v1.1.0] itzkiba.better_progression
x | [v1.1.0] itzkiba.id_hyperlinks
x | [v1.1.0] jojo989.main_menu_bg_customizer
x | [v1.0.0] mat.reference-image
x | [v1.0.0] naxrin.rgb_icons
x | [v1.2.0] prevter.bettercrash
x | [v1.0.1] relative.advanced_song_search
x | [v1.1.0] relative.custom_endscreen_text
x | [v0.1.6] rooot.custom-gamemode-colors
x | [v1.2.0] shineua.geometrize2gd
x | [v1.0.9] syzzi.click_between_frames
x | [v2.11.0] techstudent10.discord_rich_presence
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.0.0-beta.8] thesillydoggo.comment_emojis
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.3.0] uproxide.more_difficulties
x | [v1.1.2] weebify.restartbtn
x | [v1.0.1] xiyxs.recolored_music_library_songs

### Steps to Reproduce

1. Install these mods.
2. Launch the game.
3. Login (If you didnt already)
4. Click the profile button
(Thats literally it.)

### Crash Report

https://pastebin.com/HCbEvrSv

### Additional Information

First of all, i have recently reset my pc so i installed geode a few days later. I tried launching gd, installing all the mods i had, but i had an crash, its was about mods, i deleted a lot of mods but kept some i liked/used but when i opened the game and clicked my profile, it was a completely different crash! I'm not sure if this was caused by mods or not, so thats also why im posting this crash report i got today right before writing this.

**Comment by RayDeeUx** [comment] 2024-05-21 18:04
crash caused by `itzkiba.better_progression.dll`.

**Comment by ilovelampadaire** [comment] 2024-05-21 18:08
> crash caused by `itzkiba.better_progression.dll`.

Oh thanks!

**Comment by ilovelampadaire** [comment] 2024-05-21 18:08
how do i mark as resolved?

**Comment by hiimjustin000** [comment] 2024-05-21 18:09
Press "Close with comment"

**Comment by RayDeeUx** [comment] 2024-05-21 18:09
you should be able to close the issue

**Closed** 2024-05-21 18:09 UTC
Labels: crash, unverified
