### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by Noodlesy** [geode-sdk/geode#778] opened 2024-05-20 19:53 UTC
### Geode Version

idk the latest one

### Your Solution

Please add IOS support for the love of god

**Comment by Kingminer7** [comment] 2024-05-20 21:48
For the last time, its not that simple. 

TL;DR it'd be extremely inconvenient for both devs and users, so not really worth it. Possibly if iOS makes some important changes, it could happen

iOS doesn't support dynamic library loading, so basically every mod would have to be built into the app, and that would be a major issue. You'd have to update the app every single time a mod released/updated and it'd allow piracy (which geode is against)

**Comment by TheSillyDoggo** [comment] 2024-05-20 22:14
Does he know...

**Comment by FireMario211** [comment] 2024-05-20 23:03
https://en.wikipedia.org/wiki/Fake_news

**Comment by RoootTheFox** [comment] 2024-05-20 23:48
is not real, will never be real. do not believe people that tell you otherwise! refer to the link FireMario211 sent for more information!

**Comment by qimiko** [comment] 2024-05-21 00:21
you guys are weird. duplicate of #528

**Closed by qimiko** 2024-05-21 00:21 UTC
