### ISSUE TITLE
C++ Error: abnormal program termination

### ISSUE THREAD

**Issue by Thyssenkrupp234** [geode-sdk/geode#946] opened 2024-06-22 20:40 UTC
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0

### Mods Installed

None

### Expected Behavior

Game loads without any errors with geode

### Actual Behavior

Game loads, wine throws an error, and the geode mod menu is stuck on "Loading". Everything else works fine, but the error is thrown each time Geometry Dash loads, and the geode interface is stuck on "Loading".

### Steps to Reproduce

Note: This is using Whisky on macOS (Apple's Game Porting Toolkit + Wine, essentially Steam Proton but for mac) - Geode 2.x.x worked fine with this tool.

1. Install steam and geometry dash via Whisky
2. Install Geode
3. Set xinput1_4 override to be native, builtin
4. Launch geometry dash via Steam
5. Error occurs

### Additional Information

In the installer, everything was checked, and it did install the C++ frameworks. As I said before, 2.x.x worked fine before. I'm using this combo on macOS since my display refresh rate is 120hz, and the macOS GD is locked to 60hz... stupidly. I'm using an apple silicon mac as well. M3 Pro Macbook Pro.

**Comment by Thyssenkrupp234** [comment] 2024-06-22 20:41
<img width="351" alt="Screenshot 2024-06-22 at 1 40 48 PM" src="https://github.com/geode-sdk/geode/assets/76831903/773b6e39-4a60-4d9c-9832-b682a576cebc">

This is the error that is thrown.

**Comment by EmeraldLoc** [comment] 2024-06-22 21:45
Getting the same error. Here's some more logs:

<img width="726" alt="Screenshot 2024-06-22 at 4 38 33 PM" src="https://github.com/geode-sdk/geode/assets/86802223/f3f92fda-322d-487d-96f2-848b6a952809">

Running macOS Sequoia developer beta 1, on a M1 Pro Macbook Pro. Just like Thyssenkrupp234, this setup worked fine using 2.x.x. Running with Windows 10 as my windows ver, same bug occurs on windows 7, and 8.1.

**Comment by JustLongobardo** [comment] 2024-06-23 13:02
![Screenshot 2024-06-23 at 2 39 16 PM](https://github.com/geode-sdk/geode/assets/138389796/d85fd53b-07f7-4f83-a379-e6deecbcbac0)
Same error here, running gptk through whisky on Sonoma on a M2 mac mini

**Comment by annpocoyo** [comment] 2024-07-06 02:30
Has anyone found a solution, I am still struggling with this problem.

**Comment by JustLongobardo** [comment] 2024-07-06 08:32
Right now I am using VMware fusion to install windows 11 in a VM and play gd from there. Apparently the problem is the version of wine used by the gptk, because it's obsolete and you can't update it in anyway as it is a custom version to translate direct3D instructions into Metal 3 instructions

**Comment by Thyssenkrupp234** [comment] 2024-07-06 16:49
@JustLongobardo, interesting - Geometry dash crashes on parallels with 2.206. Could you please send me a direct download link to VMware Fusion? Any time I try to download it, I’m forced to create an account on a different website and it’s impossible to login. Thanks!

**Comment by JustLongobardo** [comment] 2024-07-06 18:27
This should work: https://support.broadcom.com/group/ecx/productfiles?subFamily=VMware%20Fusion&displayGroup=VMware%20Fusion%2013%20Pro%20for%20Personal%20Use&release=13.5.2&os=&servicePk=520445&language=EN

**Comment by annpocoyo** [comment] 2024-07-07 01:09
Did you use to have a VMware account? Because VMware doesn't have any direct download links, all of them are temporary or something. If you had a VMware account you can migrate it to Broadcom (you should have a email).

**Comment by JustLongobardo** [comment] 2024-07-07 08:37
I used to use a vmware account, now migrated to a broadcom account to have a license for personal use. You need a broadcom account to download the installer

**Comment by JustLongobardo** [comment] 2024-07-07 08:54
Btw, I got the file here on google drive if you need it https://drive.google.com/file/d/19erJ5Qexc3dv-bjAwh1LymeCG-ssQJYA/view?usp=share_link

**Comment by dankmeme01** [comment] 2024-07-07 13:11
@Thyssenkrupp234 @EmeraldLoc @JustLongobardo could you please try to install [this nightly build](https://github.com/geode-sdk/geode/actions/runs/9827494647) and see if it works?

The issue was one of the libraries we use relying on a DLL that was missing in versions of Wine prior to 8.13, which now should be fixed. I am unable to test it on a Mac machine, but on my Linux system Proton 6-8 now works with no issues.

**Comment by JustLongobardo** [comment] 2024-07-07 14:07
It doesn't give any error @dankmeme01 and I can download mods too

**Comment by JustLongobardo** [comment] 2024-07-07 14:08
Here's screenshots
![Screenshot 2024-07-07 at 4 07 37 PM](https://github.com/geode-sdk/geode/assets/138389796/50f0f24b-187f-43c2-95c7-be74e8458a71)
![Screenshot 2024-07-07 at 4 07 44 PM](https://github.com/geode-sdk/geode/assets/138389796/723fbadb-b85b-4964-86bd-3d22f081e0f3)

**Comment by annpocoyo** [comment] 2024-07-08 08:18
Works here as well. I guess this issue can be closed now :)
<img width="1440" alt="Screenshot 2024-07-08 at 6 18 30 PM" src="https://github.com/geode-sdk/geode/assets/68903277/2fbdd54c-8a5b-4eb7-af24-953d00dc690c">

**Closed** 2024-07-08 21:34 UTC
Labels: bug, unverified
