### ISSUE TITLE
Adding geode in iPhone solution

### ISSUE THREAD

**Issue by lucaslegamerpro** [geode-sdk/geode#1200] opened 2024-12-23 09:14 UTC
### Geode Version

1.4.2

### Your Solution

Could you release an iPhone version of geode?? Not in the app store but in the form of ida (equivalent to apk on iphone)

**Comment by qimiko** [comment] 2024-12-23 11:26
duplicate of #898

**Closed by qimiko** 2024-12-23 11:26 UTC
