### ISSUE TITLE
FEAT: Add a update all button

### ISSUE THREAD

**Issue by user1126s** [geode-sdk/geode#559] opened 2024-02-24 14:54 UTC
### Geode Version

v2.00 beta 20

### Related Problem

it is very difficult to update each mod one by one

### Your Solution

Add a update all button in the corner

### Additional Information

thats it

**Comment by TheBearodactyl** [comment] 2024-03-04 17:37
duplicate of #523

**Closed** 2024-06-22 00:16 UTC
