### ISSUE TITLE
`utils::string::replace` hangs on empty strings

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/geode#1162] opened 2024-11-17 16:05 UTC
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v4.0.0-beta

### Expected Behavior

When attempting to use `geode::utils::string::replace` on an empty string, the code should return the empty string as there is nothing to replace.

### Actual Behavior

Instead, it hangs. No crashes, just hangs on this single line of code.

### Steps to Reproduce

1. use `geode::utils::string::replace` where the original string is blank

**Comment by dankmeme01** [comment] 2024-11-17 17:15
could not reproduce the issue with the input string being blank, but if the `orig` parameter was blank, the function would indeed loop forever and hang. fixed in https://github.com/geode-sdk/geode/commit/4d5e465ade1464d2c0cd39eddd099328bd714fb6

**Closed by dankmeme01** 2024-11-17 17:15 UTC
Labels: bug, unverified
